### PR TITLE
github: Extend the CODEOWNERS

### PR DESCRIPTION
**Pull request by roosterfish**

### CODE REVIEW

**Review by tomponline — APPROVED** [review]

**Comment by tomponline** [comment]
Please sign your commits

**Comment by tomponline** [comment]
You can use your ssh key to sign

**Comment by tomponline** [comment]
https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#ssh-commit-signature-verification

**Comment by roosterfish** [comment]
@tomponline ah it was always about the signing, not the number of approvals. My bad, fixed now.

**Pull request merged**
